@startuml Massage Reservation Use Case Diagram
left to right direction
actor "Registered User" as registeredUser
rectangle "Massage Reservation" as MassageSystem {
    usecase "Register/Login" as registerlogin
    usecase "View\nMassage Shops" as viewMassageShop
    usecase "Manage\nMassage Shops" as manageMassageShop
    usecase "Manage All\nReservations" as manageAllReservation
    usecase "Manage Own\nReservations" as manageOwnReservation
    usecase "View Own\nReservations" as viewOwnReservation
    usecase "View All\nReservations" as viewAllReservation
}
viewAllReservation .> viewOwnReservation : <<include>>
manageAllReservation .> manageOwnReservation : <<include>>

registeredUser -- registerlogin
registeredUser -- viewMassageShop
registeredUser -- manageOwnReservation
registeredUser -- viewOwnReservation

actor "Non-Registered User" as nonregistered
nonregistered -- registerlogin
nonregistered -- viewMassageShop

User <|-- registeredUser
User <|-- nonregistered

actor "Admin" as admin
registerlogin -- admin
manageMassageShop -- admin
viewAllReservation -- admin
manageAllReservation -- admin
viewMassageShop -- admin

@enduml